---
title: "Chapter 3: Built-in Data Structures, Functions, and Files"
output: html_notebook
---

This chapter will cover Pythons main built-in data structures: tuples, lists, dicts, and sets.

## Data Structures and Sequences

### Tuple

A tuple is a fixed-length, immutable sequence of Python objects. You can create one with a comma-separated sequences of values:

```{python}
tup = 4, 5, 6
tup
```

When you're defining tuples in more complicated expressions, it's often necessary to enclose the values in parentheses, as in the example:

```{python}
nested_tup = (4, 5, 6), (7, 8)
nested_tup
```

You can convert any sequence or iterator to a tuple by invoking `tuple`:

```{python}
tuple([4, 0, 2])

tup = tuple("string")
tup
```

Elements can be accessed with square brackets `[]` as with most other sequence types. Python uses 0-indexing:

```{python}
tup[0]
```

Once the tuple is created it's not possible to modify which object is stored in each slot.

```{python}
tup = tuple(["foo", [1, 2], True])

tup[2] = False
```

If an object inside a tuple is mutable, such as a list, you can modify it in-place:

```{python}
tup[1].append(3)
tup
```

You can concatenate tuples using the `+` operator to produce longer tuples:

```{python}
(4, None, "foo") + (6, 0) + ("bar", )
```

Multiplying a tuple by an integer, as with lists, has the effect of concatenating together that many copies of the tuple:

```{python}
("foo", "bar") * 4
```

#### Unpacking tuples

If you try to *assign* to a tuple-like expression of variables, Python will attempt to *unpack* the value on the righthand side of the equals sign:

```{python}
tup = (4, 5, 6)

a, b, c = tup

b
```

With this functionality you can easily swap variable names. In Python this is done like this:

```{python}
a, b = 1, 2

a

b

b, a = a, b

a

b
```

A common use of variable unpacking is iterating over sequences of tuples or lists:

```{python}
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

for a, b, c in seq:
    print("a = {0}, b = {1}, c = {2}".format(a, b, c))

```

If you want to pick a few elements from the beginning of tuple you can use the special syntax `*rest`.

```{python}
values = 1, 2, 3, 4, 5

a, b, *rest = values

a, b

rest
```

Sometimes the `_` is used for unwanted variables:

```{python}
a, b, *_ = values

_
```

#### Tuple methods

Tuples have very limited instance methods. One useful one is `count`, which counts the number of occurrences of a value:

```{python}
a = (1, 2, 2, 2, 3, 4, 2)

a.count(2)
```

### List

In contrast with tuples, lists are variable-length and their contents can be modified in-place. You define them using brackets `[]` or using the `list` type function:

```{python}
a_list = [2, 3, 7, None]

tup = ("foo", "bar", "baz")

b_list = list(tup)

b_list

b_list[1] = "peekaboo"

b_list
```

The `list` function is frequently used in data processing as a way to materialize an iterator or generator expression:

```{python}
gen = range(10)

gen

list(gen)
```

#### Adding and removing elements

Elements can be appended to the end of the list with the `append` method:

```{python}
b_list.append("dwarf")

b_list
```

Using `insert` you can insert an element at a specific location in the list:

```{python}
b_list.insert(1, "red")

b_list
```

The inverse of `insert` is `pop`, which removes and returns an elements at a particular index:

```{python}
b_list.pop(2)

b_list
```

Elements can be removed by value with `remove`, which locates the first such value and removes it from the list:

```{python}
b_list.append("foo")

b_list

b_list.remove("foo")

b_list
```

#### Concatenating and combining lists

Adding two lists together with `+` concatenates them:

```{python}
[4, None, "foo"] + [7, 8, (2, 3)]
```

You can use `extent` to append multiple elements to an existing list:

```{python}
x = [4, None, "foo"]

x.extend([7, 8, (2, 3)])

x
```

#### Sorting

You can sort a list in-place by calling its `sort` function:

```{python}
a = [7, 2, 5, 1, 3]

a.sort()

a
```

You can also pass a secondary *sort key* which is a function that produces a value to use to sort the objects. For example, we could sort a collection of strings by lengths:

```{python}
b = ["saw", "small", "He", "foxes", "six"]

b.sort(key = len)

b
```

#### Binary search and maintaining a sorted list

The built-in `bisect` module implements binary search and insertion into a sorted list. `bisect.bisect` finds the location where an element should be inserted to keep it sorted, while `bisect.insort` actually inserts the element into that location:

```{python}
import bisect

c = [1, 2, 2, 2, 3, 4, 7]

bisect.bisect(c, 2)

bisect.bisect(c, 5)

bisect.insort(c, 6)

c
```

#### Slicing

You can select sections of most sequence types by using slice notation, which in its basic form consists of `start:stop` passed to the indexing operator `[]`:

```{python}
seq = [7, 2, 3, 7, 5, 6, 0, 1]

seq[1:5]
```

Slices can also be assigned to a with sequence:

```{python}
seq[3:4] = [6, 3]

seq
```

You can also omit the start and stop:

```{python}
seq[:5]

seq[3:]
```

Negative indices slice the sequence relative to the end:

```{python}
seq[-4:]

seq[-6:-2]
```

A step is used to take every other element:

```{python}
seq[::2]
```

### Built-in Sequence Functions

#### `enumerate`

It's common when iterating over a sequence to want to keep track of the index of the current item:

```{python}
i = 0
for value in collection:
    # do something with value
    i += 1
    
```

Since this is so common, Python has a built-in function, `enumerate`, which returns a sequence of (`i`, `value`) tuples:

```{python}
for i, value in enumerate(collection):
    # do something with value
```

A helpful pattern that uses `enumerate` is computing a `dict` mapping the values of a sequence to their locations in the sequence:

```{python}
some_list = ["foo", "bar", "baz"]
mapping = {}

for i, v in enumerate(some_list):
    mapping[v] = i
    
mapping
```

#### sorted

The `sorted` function returns a new sorted list from the elements of any sequence:

```{python}
sorted([7, 1, 2, 6, 0, 3, 2])

sorted("horse race")
```

#### zip

`zip` pairs up elements of a number of lists, tuples, or other sequences to create a list of tuples:

```{python}
seq1 = ["foo", "bar", "baz"]
seq2 = ["one", "two", "three"]

zipped = zip(seq1, seq2)
list(zipped)
```

A common use of `zip` is simultaneously iterating over multiple sequences, possibly also combined with `enumerate`:

```{python}
for i, (a, b) in enumerate(zip(seq1, seq2)) :
    print("{0}: {1}, {2}".format(i, a, b))

```

#### reversed

`reversed` iterates over the elements of a sequence in reverse order:

```{python}
list(reversed(range(10)))
```

#### dict

`dict` is likely the most important built-in Python data structure. A more common name for it is *hash map* or *associative array*. It is a flexibly sized collection of *key-value* pairs, where *key* and *value* are Python objects. One approach for creating one is to use curly braces `{}` and colons to separate keys and values:

```{python}
empyt_dict = {}

d1 = {"a" : "some value", "b" : [1, 2, 3, 4]}
d1
```

You can access or insert elements using the same syntax as for the tuple:

```{python}
d1[7] = "an integer"

d1

d1["b"]
```

You can check if a `dict` contains a key using the same syntax used for checking whether a list or tuple contains a value:

```{python}
"b" in d1
```

You can delete values using the `del` keyword or the `pop` method (which returns the value and deletes the key):

```{python}
d1[5] = "some value"
d1

d1["dummy"] = "another value"
d1

del d1[5]
d1

ret = d1.pop("dummy")
ret

d1
```

The `keys` and `values` method give you iterators of the dict's keys and values, respectively.

```{python}
list(d1.keys())

list(d1.values())
```

You can merge one dict into another using the `update` method:

```{python}
d1.update({"b" : "foo", "c" : 12})
d1
```

The `update` method changes dicts in-place, so any existing keys in the data passed to `update` will have their old values discarded.

#### Creating dicts from sequences

It's common to occasionally end up with two sequences that you want to pair up element-wise in a dict.

```{python}
mapping = {}
for key, value in zip(key_list, value_list):
    mapping[key] = value

```

The `dict` function accepts a list of 2-tuples:

```{python}
mapping = dict(zip(range(5), reversed(range(5))))
mapping
```

#### Default values

It's common to have logic like:

```{python}
if key in some_dict:
    value = some_dict[key]
else: 
    value = default_value

```

The dict methods `get` and `pop` can take a default value to be returned, so that the above `if-else` block can be written simply as:

```{python}
value = some_dict.get(key, default_value)
```

`get` by default will return `None` if the key is not present, while `pop` will raise an exception. With *setting* values, a common case is for the values in a dict to be other collections, like lists. For example, you could imagine categorizing a list of words by their first letters as a dict of lists:

```{python}
words = ["apple", "bat", "bar", "atom", "book"]
by_letter = {}

for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)
        
by_letter
```

The `setdefault` dict method is for this purpose. We can rewrite this `for` loop as:

```{python}
for word in words:
    letter = word[0]
    by_letter.setdefault(letter, []).append(word)
    
by_letter
```

`defaultdict` from `collections` makes the even easier:

```{python}
from collections import defaultdict
by_letter = defaultdict(list)
for word in words:
    by_letter[word[0]].append(word)
    
by_letter
```

#### Valid dict key types

You can check if an object is hasable with the `hash` function:

```{python}
hash("srting")
```

#### set

A set is an unordered collection of unique elements. A set can be created in two ways:

```{python}
set([2, 2, 2, 1, 3, 3])

{2, 2, 2, 1, 3, 3}
```

Sets support *set operations* like union, intersection, difference, and symmetric difference:

```{python}
a = {1, 2, 3, 4, 5}

b = {3, 4, 5, 6, 7, 8}

a.union(b)

a | b
```

### List, Set, and Dict Comprehensions

*List comprehensions* allow you to concisely form a new list by filter the elements of a collection.

```{python, eval = FALSE}
[expr for val in collection if condition]
```

This is equivalent to the following `for` loop:

```{python}
result = []
for val in collection:
    if condition:
        result.append(expr)
        

```

For example, given a list of string, we could filter out strings with length 2 or less and also convert them to uppercase like this:

```{python}
strings = ["a", "as", "bat", "car", "dove", "python"]

[x.upper() for x in strings if len(x) > 2]
```

Set and dict comprehensions are a natural extension, producing sets and dicts in an idiomatically similar way instead of lists. A dict comprehension looks like this:

```{python, eval = FALSE}
dict_comp = {key-expr : value-expr for value in collection if condition}
```

A set comprehension looks like the equivalent list comprehension except with curly braces instead of square brackets:

```{python, eval = FALSE}
set_comp = {expr for value in collecrion if condition}
```

Suppose we wanted a set containing just the lengths of the strings contained in the collection; we can do this with a set comprehension:

```{python}
unique_lengths = {len(x) for x in strings}
unique_lengths
```

We could also express this more functionally using the `map` function:

```{python}
set(map(len, strings))
```

We could create a lookup map of these strings to their locations in the list:

```{python}
loc_mapping = {val : index for index, val in enumerate(strings)}
loc_mapping
```

#### Nested list comprehensions

Suppose we have a list of lists containing names:

```{python}
all_data = [["John", "Emily", "Michael", "Mary", "Steven"],
            ["Maria", "Juan", "Javier", "Natalia", "Pilar"]]
```

Suppose we want to get a single list of all names with two or more `e`'s in them. We could do this with a `for` loop:

```{python}
names_of_interest = []
for names in all_data:
    enough_es = [name for name in names if name.count("e") >= 2]
    names_of_interest.extend(enough_es)
    
names_of_interest
```

But, you can wrap this whole operation in a single *nested list comprehension*:

```{python}
result = [name for names in all_data for name in names
          if name.count("e") >= 2]

result
```

## Functions

Functions are declared with the `def` keyword and returned from with the `return` keyword:

```{python, eval = FALSE}
def my_function(x, y, z = 1.5):
    if z > 1:
        return z * (x + y)
    else:
        return z / (x + y)
      
```

Functions can have positional arguments and keyword arguments:

```{python}
my_function(5, 6, z = 0.7)
my_function(3.14, 7, 3.6)
my_function(10, 20)
```

### Namespaces, Scope, and Local Functions

Functions can access variables in two different scopes: *global* and *local*. A more descriptive name describing a variable scope in Python is a *namespace*. Consider this function:

```{python}
def func():
    a = []
    for i in range(5):
        # TODO: write code...
        a.append(i)
        
```

When `func()` is called, the empty list `a` is created, ive elements are appended, and then `a` is destroyed when the function exits. Suppose instead we had:

```{python}
a = []
def func():
    for i in range(5):
      a.append(i)
      

```

Each call to `func` will modify the list `a`:

```{python}
func()

a

func()

a
```

Assigning variables outside of the function's scope is possible, but those variables must be declared as global via the `global` keyword:

```{python}
a = None

def bind_a_variable():
    global a
    a = []
bind_a_variable()

print(a)
```

### Returning Multiple Values

### Functions are Objects

Suppose we needed to do some data cleaning to this string:

```{python}
states = ["  Alabama    ", "Georgia!", "Georgia", "georgia", "FlOrIda",
          "south carolina##", "West virginia?"]
```

This can be cleaned with the built-in string methods along with the `re` standard library module:

```{python}
import re

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub("[!#?]", "", value)
        value = value.title()
        result.append(value)
    return result
  
clean_strings(states)
```

### Anonymous (Lambda) Functions

Lambda functions are a way of writing functions consisting of a single statement, the result of which is the return value.

```{python}
def short_functions(x):
    return x * 2
  

equiv_anon = lambda x: x * 2
```
