---
title: "Chapter 4: NumPy Basics: Arrays and Vectorized Computation"
output: html_notebook
---

## The NumPy ndarray: A Multidimensional Array Object

An array is a container for large datasets in Python.

```{python}
import numpy as np

# generate some random data
data = np.random.randn(2, 3)
data
```

No do math with `data`:

```{python}
data * 10

data + data
```

All arrays have a shape and type:

```{python}
data.shape

data.dtype
```

### Creating ndarrays

You create an array with the `array` function. We can convert a list to an array like this:

```{python}
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1
```

Nested sequences a converted in a multidimensional array:

```{python}
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

arr2
```

`arange` is an array-valued version of the built-in Python `range` function:

```{python}
np.arange(15)
```

### Data Types for ndarrays

The *data type* or `dtype` is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data:

```{python}
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

arr1.dtype
```

You can convert, or cast, an array from one dtype to another using the `astype` method:

```{python}
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

float_arr = arr.astype(np.float64)
float_arr.dtype
```

### Arithmatic with NumPy Arrays

Any arithmetic operations between equal-size arrays applies the operation element-wise, which is called vectorization:

```{python}
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

arr * arr
```

### Basic Indexing and Slicing

One-dimensional arrays act similar to Python lists:

```{python}
arr = np.arange(10)

arr

arr[5]

arr[5:8]

arr[5:8] = 12

arr
```

In Python, array slices are *views* on the original array. The data is not copied.

```{python}
arr_slice = arr[5:8]
arr_slice

arr_slice[1] = 12345
arr
```

The "bare" slice `[:]` will assign to all values in an array:

```{python}
arr_slice[:] = 64
arr
```

With higher dimensional arrays, you have more options:

```{python}
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d
```

You can pass a comma-separated list of indices to select individual elements:

```{python}
arr2d[0, 2]
```

If you omit the later indices in higher dimensional arrays, the returned object will have a lower dimensional ndarray:

```{python}
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

arr3d[0]
```

#### Indexing with slices

```{python}
arr

arr[1:6]

arr2d[:2]
```

### Boolean Indexing

```{python}
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

data = np.random.randn(7, 4)

names

data
```

If we wanted to select all the rows with the name "Bob" we could:

```{python}
names == "Bob"

data[names == "Bob"]
```

Select everything but "Bob" like this:

```{python}
names != "Bob"
```

Selecting data from an array by boolean indexing *always* creates a copy of the data.

To set all nagative values in `data` to 0, we only need to do this:

```{python}
data[data < 0] = 0
data
```

### Fancy Indexing

*Fancy indexing* is a term adopted by NumPy to describe indexing using integer arrays.

```{python}
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
    

arr
```

To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers in the desired order:

```{python}
arr[[4, 3, 0, 6]]
```

### Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything.

```{python}
arr = np.arange(15).reshape((3, 5))
arr

arr.T
```

## Universal Functions: Fast Element-Wise Array Functions

A universal function is a function that preforms element-wise operations on data in ndarrays like `sqrt` or `exp`.

```{python}
arr = np.arange(10)
arr

np.sqrt(arr)
np.exp(arr)
```

## Array-Oriented Programming with Arrays

Suppose we wished to evaluate the function `sqrt(x^2 + y^2)` across a regular grid of values.

```{python}
points = np.arange(-5, 5, 0.01)

xs, ys = np.meshgrid(points, points)

ys
```

To evaluate the express, we write:

```{python}
z = np.sqrt(xs ** 2 + ys ** 2)
z
```

Here we'll use matplotlib to visualize this array:

```{python}
import matplotlib.pyplot as plt

plt.imshow(z, cmap = plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.show()
```

### Expressing Conditional Logic as Array Operations

The `numpy.where` function is a vectorized version of the ternary expression `x if conditional else y`. Suppose we had a boolean array and two arrays of values

```{python}
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])
```

Suppose we wanted to take a value from `xarr` whenever the corresponding value in `cond` is `True`, and otherwise take the value from `yarr`. A list comprehension doing this might look like:

```{python}
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result
```

This can be written more concisely with `np.where`.

```{python}
result = np.where(cond, xarr, yarr)
result
```

### Mathematical and Statistical Methods

Here we generate some normally distributed data and compute some aggregate statistics:

```{python}
arr = np.random.randn(5, 4)
arr

arr.mean()

np.mean(arr)

arr.sum()

np.sum(arr)
```

Functions like `mean` and `sum` take an optional `axis` argument that computes the statistic over the given axis, resulting in an array with one fewer dimension:

```{python}
arr.mean(axis = 1)

arr.mean(axis = 0)
```

Here, `arr.mean(axis = 1)` means "compute mean across the columns" where `arr.mean(axis = 0)` means "compute the mean down the rows." Other methods like `cumprod` do not aggregate, instead producing an array of intermediate results.

```{python}
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()
```

### Methods for Boolean Arrays

Sum can be used to count `True` values in a boolean array:

```{python}
arr = np.random.randn(100)

(arr > 0).sum()
```

### Sorting

NumPy arrays can be sorted in-place with the `sort` method:

```{python}
arr = np.random.randn(6)
arr

arr.sort()
arr
```

### Unique and Other Set Logic

```{python}
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
np.unique(names)

ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)
```

## File Input and Output with Arrays

NumPy uses `np.load` and `np.save` to load and save data. The file extension used is `.npy`.

## Linear Algebra

The function `dot` gives the dot product.

```{python}
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

x
y
x.dot(y)
```

## Pseudorandom Number Generation

You can get a 4x4 array of samples from the standard normal distribution using `normal`:

```{python}
sample = np.random.normal(size = (4, 4))
sample
```

## Example: Random Walks

Consider a simple random walk starting at 0 with steps of 1 and -1 occurring with equal probability.

```{python}
nsteps = 1000
draws = np.random.radint(0, 2, size = nsteps)
steps = np.where(draws > 0, 1, -1)
wwalk = steps.cumsum()
```
